# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'mealplanappiOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for mealplanappiOS
  pod 'Socket.IO-Client-Swift’, ‘~> 8.1.1'
end
